### ISSUE TITLE
pgbackrest stanza-create - command terminated with exit code 49

### ISSUE THREAD

**Issue by anshudutta** [CrunchyData/crunchy-containers#1156]
**Describe the bug**
Error when pgbackrest is enabled. Create stanza job fails. The storage class is set to `volumeBindingMode: WaitForFirstConsumer`

```
time="2019-12-04T04:38:04Z" level=info msg="pgo-backrest starts"
time="2019-12-04T04:38:04Z" level=info msg="debug flag set to false"
time="2019-12-04T04:38:04Z" level=info msg="backrest stanza-create command requested"
time="2019-12-04T04:38:34Z" level=info msg="sleeping 30 seconds to avoid race with PG during startup"
time="2019-12-04T04:38:34Z" level=info msg="command to execute is [pgbackrest stanza-create ]"
time="2019-12-04T04:38:34Z" level=info msg="command is pgbackrest stanza-create  "
time="2019-12-04T04:38:35Z" level=error msg="command terminated with exit code 49"
time="2019-12-04T04:38:35Z" level=info msg="output=[]"
time="2019-12-04T04:38:35Z" level=info msg="stderr=[]"
time="2019-12-04T04:38:35Z" level=error msg="command terminated with exit code 49"

```
PGO.yaml
```
Cluster:
  PrimaryNodeLabel:
  ReplicaNodeLabel:
  CCPImagePrefix: crunchydata
  Metrics: false
  Badger: false
  CCPImageTag: centos7-11.4-2.3.3
  Port: 5432
  User: alchemy
  Database: userdb
  PasswordAgeDays: 60
  PasswordLength: 8
  Strategy: 1
  Replicas: 2
  ArchiveMode: false
  ArchiveTimeout: 60
  ServiceType: ClusterIP
  Backrest: true
  BackrestPort: 2022
  Autofail: false
  AutofailReplaceReplica: false
  LogStatement: none
  LogMinDurationStatement: 60000
PrimaryStorage: gkessd
XlogStorage: gkestandard
BackupStorage: gkestandard
ReplicaStorage: gkestandard
BackrestStorage: gkestandard
Storage:
  gkessd:
    AccessMode: ReadWriteOnce
    Size: 8G
    StorageType: dynamic
    StorageClass: ssd-alchemy
    Fsgroup: 26
  gkestandard:
    AccessMode: ReadWriteOnce
    Size: 200Gi
    StorageType: dynamic
    StorageClass: pd-standard-alchemy
    Fsgroup: 26
DefaultContainerResources:
DefaultLoadResources:
DefaultLspvcResources:
DefaultRmdataResources:
DefaultBackupResources:
DefaultPgbouncerResources:
DefaultPgpoolResources:
ContainerResources:
  small:
    RequestsMemory: 512Mi
    RequestsCPU: 0.1
    LimitsMemory: 512Mi
    LimitsCPU: 0.1
  large:
    RequestsMemory: 2Gi
    RequestsCPU: 2.0
    LimitsMemory: 2Gi
    LimitsCPU: 4.0
Pgo:
  AutofailSleepSeconds: 9
  Audit: false
  LSPVCTemplate: /pgo-config/pgo.lspvc-template.json
  LoadTemplate: /pgo-config/pgo.load-template.json
  COImagePrefix: crunchydata
  COImageTag: centos7-3.5.0

```
Storage classes
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-standard-alchemy
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-alchemy
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-ssd
```
Volumes are bound
```
NAME                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
alchemy-database                        Bound    pvc-7a501bc9-165a-11ea-9a8f-42010a000006   8Gi        RWO            ssd-alchemy           6m36s
alchemy-database-backrest-shared-repo   Bound    pvc-7c3236fe-165a-11ea-9a8f-42010a000006   200Gi      RWO            pd-standard-alchemy   6m33s
alchemy-database-pnuo                   Bound    pvc-7e7b3092-165a-11ea-9a8f-42010a000006   200Gi      RWO            pd-standard-alchemy   6m29s
alchemy-database-srih                   Bound    pvc-808c2e62-165a-11ea-9a8f-42010a000006   200Gi      RWO            pd-standard-alchemy   6m26s

```
Pods
```
alchemy-database-569cf57dc6-mljzt                        3/3     Running            0          7m59s
alchemy-database-backrest-shared-repo-85fcbdfbf4-4lr4t   2/2     Running            0          7m59s
alchemy-database-pgpool-5788999b88-dhfk2                 2/2     Running            0          7m58s
alchemy-database-pnuo-bb96474c8-v2pgn                    3/3     Running            0          7m55s
alchemy-database-srih-6d99568fcb-89j89                   3/3     Running            0          7m52s
alchemy-database-stanza-create-95n22                     1/2     Error              0          7m9s
alchemy-pgo-admin-cf554f8d5-tjdtt                        1/1     Running            0          8m5s
postgres-operator-pgo-545f84d56b-67hqn                   4/4     Running            0          8m21s

```
**Expected behavior**
It should be able to create stanza

**Screenshots**

**Please tell us about your environment:**

* Operating System: centos:7
* Where is this running : GCP
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: centos7-3.5.4
* PostgreSQL Version: 3.5.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.12.10-gke.17

**Additional context**
We have istio as service mesh

I get error 49 when I do this on `alchemy-database-backrest-shared-repo` pod
```
$ pgbackrest check
ERROR [049]: : found name '2.13' in protocol greeting instead of expected '2.08'
```
```
$ pgbackrest info
stanza: db
    status: error (missing stanza path)
```
