### ISSUE TITLE
_FILE env var for Docker Secrets support, entrypoint.sh and examples included.

### ISSUE THREAD

**Issue by jasonrichdarmawan** [CrunchyData/crunchy-containers#1238]
**What is the motivation or use case for the feature?**

Support for Docker Secrets, so we don't have to put the secrets in env var.

**Describe any alternatives you've considered**

[Official Docs](https://crunchydata.github.io/crunchy-containers/stable/container-specifications/crunchy-postgres/) does not show support for _FILE env var.

I considered to use GitHub secrets but the idea of hosting the secrets to a third party. I believe it should be the last option.

**Describe the solution you'd like**

Add to `examples/secrets/docker-entrypoint.sh`
```
#!/usr/bin/env bash

# https://success.docker.com/article/use-a-script-to-initialize-stateful-container-data
# https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh
# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
    local var="$1"
    local fileVar="${var}_FILE"
    local def="${2:-}"
    if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
        echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
        exit 1
    fi
    local val="$def"
    if [ "${!var:-}" ]; then
        val="${!var}"
    elif [ "${!fileVar:-}" ]; then
        val="$(< "${!fileVar}")"
    fi
    export "$var"="$val"
    unset "$fileVar"
}

# Loads various settings that are used elsewhere in the script
# This should be called before any other functions
docker_setup_env() {
    file_env 'PG_PRIMARY_PASSWORD'
    file_env 'PG_PASSWORD'
    file_env 'PG_ROOT_PASSWORD'
}

# call the function
docker_setup_env

.... other bash line
```

Add to `docker/examples/secrets/docker-compose.yml`
```
version: "3.4" # lastest version before network.external.name env var got depreceated

services:
  db:
    image: crunchdata/cruncy-postgres:centos7-12.3-4.3.2
    entrypoint: ["./docker-entrypoint.sh", "postgres"] # _FILE env var support
    enivornment:
      - PG_ROOT_PASSWORD_FILE=/run/secrets/dbrootpw
```

**Please tell us about your environment:**

* Where is this running ( Local , Cloud Provider) Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos7-12.3-4.3.2
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Docker
* Platform Version: 19.03.8
