### ISSUE TITLE
stanza-create pod fails

### ISSUE THREAD

**Issue by jamessewell** [CrunchyData/crunchy-containers#1345]
**Describe the bug**
When using the Crunchy Containers built from the repo  the stanza-create pod fails into an error state, from the logs:

```
ssh: connect to host 172.21.2.32 port 22: Connection refused\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"
```

If I use the identically versioned containers from the  registry.developers.crunchydata.com then everything works fine.

I thought that I should be able to SSH from the backrest-repo container to the postgres container - but this does not work.

I'm using the following YAML to bootstrap my cluster:

```
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: mslam
  labels:
    crunchy-pgha-scope: mslam
    deployment-name: mslam
    name: mslam
    pg-cluster: mslam
    pgo-version: 4.6.2
    pgouser: admin
  name: mslam
  namespace: pgo
spec:
  BackrestStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: "cinder-csi"
    storagetype: dynamic
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: mslam
    size: 1G
    storageclass: "cinder-csi"
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: "cinder-csi"
    storagetype: dynamic
    supplementalgroups: ""
  annotations: {}
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: harbor.tools.local/mslam-lbs
  ccpimagetag: centos8-13.2-4.6.2
  clustername: mslam
  database: mslam
  exporterport: "9187"
  limits: {}
  name: mslam
  namespace: pgo
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: docker.io/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  port: "5432"
  tolerations: []
  user: hippo
  userlabels:
    pgo-version: 4.6.2
```

Containers are built as per the spec, with the following inputs:

```
export GOPATH=$HOME/cdev        # set path to your new Go workspace
export GOBIN=$GOPATH/bin        # set bin path
export PATH=$PATH:$GOBIN        # add Go bin path to your overall path
export CCP_BASEOS=centos8       # centos8 for CentOS, ubi8 for Red Hat Universal Base Image
export CCP_PGVERSION=13        # The PostgreSQL major version
export CCP_PG_FULLVERSION=13.2
export CCP_POSTGIS_VERSION=3.0
export CCP_BACKREST_VERSION=2.31
export CCP_VERSION=4.6.2
export CCP_IMAGE_PREFIX=harbor.tools.local/mslam-lbs # Prefix to put before all the container image names
export CCP_IMAGE_TAG=$CCP_BASEOS-$CCP_PG_FULLVERSION-$CCP_VERSION   # Used to tag the images
export CCP_POSTGIS_IMAGE_TAG=$CCP_BASEOS-$CCP_PG_FULLVERSION-$CCP_POSTGIS_VERSION-$CCP_VERSION # Used to tag images that include PostGIS
export CCPROOT=$GOPATH/src/github.com/crunchydata/crunchy-containers    # The base of the clone github repo
```
