### ISSUE TITLE
timescaledb_toolkit in the 5.0 Operator

### ISSUE THREAD

**Issue by jhualpa** [CrunchyData/crunchy-containers#1507]
I have the requirement to use timescaledb_toolkit(https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/) on top of timescaledb on a cluster running Crunchy PostgreSQL for Kubernetes.
I thought with this lines will work:

```
patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: 'timescaledb,timescaledb_toolkit'
          timescaledb.license: apache
```

However timescaledb_toolkit extension is not installed as part of Crunchy PostgreSQL for Kubernetes so I get an error, so is there any way to install it on a running cluster ? Has somebody been through a similar situation of not having an extension needed on the images ? Should I create my own image based on https://github.com/CrunchyData/crunchy-containers/blob/master/build/postgres/Dockerfile#L52 and add the extension I need ?
