### ISSUE TITLE
pgAdmin 'ServerManager' object has no attribute 'user_info'

### ISSUE THREAD

**Issue by nniehoff** [CrunchyData/crunchy-containers#1542]
**Describe the bug**

When standing up a new HA db with pgbouncer and pgadmin enabled following the guides and logging in to pgAdmin I receive an error `'ServerManager' object has no attribute 'user_info'`

**To Reproduce**

1. Create a cluster with the attached yaml (see first comment)
3. Log in to pgAdmin as db@pgo
4. Browse to the database

**Expected behavior**

I'm able to browse the database

**Screenshots**

<img width="1301" alt="Screenshot 2023-08-19 at 9 11 04 AM" src="https://github.com/CrunchyData/crunchy-containers/assets/14947575/67812814-edab-4ab2-b0a8-fb7f9289d13c">

**Please tell us about your environment:**

* Operating System: Ubuntu 22.04
* Where is this running ( Local, Cloud Provider) K0s Cluster
* Storage being used (NFS, Hostpath, Gluster, etc): Hosstpath
* Container Image Tag: `registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-16`
* PostgreSQL Version: `registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.3-3`
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.27
* Helm Chart Version: pgo-5.4.1

**Additional context**

pgAdmin is version 4.x and version 7.x is out, a little googling suggest maybe a newer image would help.  I'm unable to find available tags for the `registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4` but I suspect if a newer version is available this would fix my issue.

**Comment by nniehoff** [comment]
```
  ---
  apiVersion: "postgres-operator.crunchydata.com/v1beta1"
  kind: "PostgresCluster"
  metadata:
    name: "db"
  spec:
    postgresVersion: 15
    instances:
      - name: "db"
        replicas: 3
        dataVolumeClaimSpec:
          storageClassName: "manual"
          selector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: "db"
              postgres-operator.crunchydata.com/instance-set: "db"
          accessModes:
          - "ReadWriteOnce"
          resources:
            requests:
              storage: 1Gi
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: "db"
                    postgres-operator.crunchydata.com/instance-set: "db"
    backups:
      pgbackrest:
        repos:
        - name: "repo1"
          volume:
            volumeClaimSpec:
              accessModes:
              - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
    proxy:
      pgBouncer:
        replicas: 2
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: "db"
                    postgres-operator.crunchydata.com/role: "pgbouncer"
    userInterface:
      pgAdmin:
        dataVolumeClaimSpec:
          accessModes:
            - 'ReadWriteOnce'
          resources:
            requests:
              storage: 1Gi
```
