### ISSUE TITLE
backup - mkdir: cannot create directory (...) Permission denied

### ISSUE THREAD

**Issue by albertocsm** [CrunchyData/crunchy-containers#338]
i'm trying to run crunchy-backup on an in-house k8s cluster with a **host volume** mount.
k8s artifact is copied bellow (1)

I get the following error
```
+ ose_hack
++ id -u
+ export USER_ID=26
+ USER_ID=26
++ id -g
+ export GROUP_ID=26
+ GROUP_ID=26
+ envsubst
+ export LD_PRELOAD=/usr/lib64/libnss_wrapper.so
+ LD_PRELOAD=/usr/lib64/libnss_wrapper.so
+ export NSS_WRAPPER_PASSWD=/tmp/passwd
+ NSS_WRAPPER_PASSWD=/tmp/passwd
+ export NSS_WRAPPER_GROUP=/etc/group
+ NSS_WRAPPER_GROUP=/etc/group
+ BACKUPBASE=/pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups
+ '[' '!' -d /pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups ']'
+ echo 'creating BACKUPBASE directory...'
+ mkdir -p /pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups
creating BACKUPBASE directory...
mkdir: cannot create directory '/pgdata': Permission denied
BACKUP_LABEL is set to  crunchybackup
+ [[ ! -v BACKUP_LABEL ]]
+ BACKUP_LABEL=crunchybackup
+ echo 'BACKUP_LABEL is set to ' crunchybackup
++ date +%Y-%m-%d-%H-%M-%S
+ TS=2017-12-07-14-51-58
+ BACKUP_PATH=/pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58
+ mkdir /pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58
mkdir: cannot create directory '/pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58': Permission denied
/pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58
+ echo /pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58
+ export PGPASSFILE=/tmp/pgpass
+ PGPASSFILE=/tmp/pgpass
+ echo '*:*:*:master:RXisH6SRJiM1eNM5'
+ chmod 600 /tmp/pgpass
+ chown 26:26 /tmp/pgpass
+ pg_basebackup --label=crunchybackup --xlog --pgdata /pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58 --host=postgresql-crunchy-master.default.svc.cluster.local --port=5432 -U master
pg_basebackup: could not access directory "/pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58": Permission denied
+ chown -R 26:26 /pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58
chown: cannot access '/pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58': Permission denied
+ chmod -R o+rx /pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58
chmod: cannot access '/pgdata/postgresql-crunchy-master.default.svc.cluster.local-backups/2017-12-07-14-51-58': Permission denied
backup has ended!
+ echo 'backup has ended!'
```

as far as i can tell, this happens because the user that executes the `start-backupjob` script is `postgres` (user id 26).
i've changed the user that runs the process and that seems to fix the problem.

of course i don't want make this "hack" to have this working.
am i'm missing something here or is in fact `postgres` not the adequate user to execute this script?

(1)
```
---
  apiVersion: "batch/v1"
  kind: Job
  metadata:
    name: postgres-crunchy-backup
  spec:
    template:
      metadata:
        name: "postgres-crunchy-backup"
      spec:
        volumes:
          -
            hostPath:
              path: /kubernetes/storage/default/postgresql-crunchy-backup
            name: pgdata
        containers:
          -
            env:
              -
                name: BACKUP_HOST
                value: postgresql-crunchy-master.default.svc.cluster.local
              -
                name: BACKUP_USER
                value: a-user
              -
                name: BACKUP_PASS
                value: "a-user-pswd" 
              -
                name: BACKUP_PORT
                value: "5432"
            image: "crunchydata/crunchy-backup:centos7-9.5-1.3.0"
            imagePullPolicy: Always
            name: postgres-crunchy-backup
            volumeMounts:
              -                
                mountPath: /pgdata
                name: pgdata
                readOnly: false
        nodeSelector:
          kubernetes.io/hostname: n2.k8s.cashyt        
        restartPolicy: Never
```
