### ISSUE TITLE
crunchy-backup report error

### ISSUE THREAD

**Issue by swimablefish** [CrunchyData/crunchy-containers#343]
I created a primary-replica cluster in kubernetes. It worked well.
When I run crunchy-backup and BACKUP_HOST is specified to primary or replica, it said

" pg_basebackup: could not connect to server: FATAL:  no pg_hba.conf entry for replication connection from host "172.16.0.0", user "postgres", SSL off"

If I specified the BACKUP_HOST as pg-pool, it reported

"pg_basebackup: could not connect to server: FATAL:  database "replication" does not exist"

**Comment by swimablefish** [comment]
Someone said it should add pg_hba.conf in server side. But I couldn't find how to config in server side.

**Comment by jmccormick2001** [comment]
are you running the backup in the same Kube cluster as where you are running primary-replica?   If so, you should be able to specify a value of 'ms-primary' for the BACKUP_HOST environment variable if you are running the primary-replica example.

**Comment by swimablefish** [comment]
Yes, I ran in the same k8s cluster. I rename the service name as primary and replica.
```
kubectl get all -n crunchy
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/pg-pool    1         1         1            1           1h
deploy/pg-watch   1         1         1            1           1h
deploy/replica    1         1         1            1           1h

NAME                    DESIRED   CURRENT   READY     AGE
rs/pg-pool-fc868d444    1         1         1         1h
rs/pg-watch-d97c66468   1         1         1         1h
rs/replica-86dd5ddb8d   1         1         1         1h

NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/pg-pool    1         1         1            1           1h
deploy/pg-watch   1         1         1            1           1h
deploy/replica    1         1         1            1           1h

NAME                    DESIRED   CURRENT   READY     AGE
rs/pg-pool-fc868d444    1         1         1         1h
rs/pg-watch-d97c66468   1         1         1         1h
rs/replica-86dd5ddb8d   1         1         1         1h

NAME             DESIRED   SUCCESSFUL   AGE
jobs/pg-backup   1         1            2m

NAME                          READY     STATUS    RESTARTS   AGE
po/pg-pool-fc868d444-zv8sq    1/1       Running   0          1h
po/pg-watch-d97c66468-vq6hj   1/1       Running   0          1h
po/primary                    1/1       Running   0          1h
po/replica-86dd5ddb8d-f2lcv   1/1       Running   0          1h

NAME          TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
svc/pg-pool   NodePort   10.96.242.224    <none>        5432:30878/TCP   1h
svc/primary   NodePort   10.100.2.78      <none>        5432:31748/TCP   1h
svc/replica   NodePort   10.100.113.205   <none>        5432:30511/TCP   1h
```

Here is the yaml file of backup job
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pg-backup
  namespace: crunchy
spec:
  template:
    metadata:
      name: pg-backup
      labels:
        app: pg-backup
    spec:
      securityContext:
        supplementalGroups:
          - 65534
      containers:
      - name: pg-backup
        image: crunchydata/crunchy-backup:centos7-9.6.6-1.7.0
        imagePullPolicy: IfNotPresent
        env:
        - name: BACKUP_USER
          value: "postgres"
        - name: BACKUP_PASS
          value: "password"
        - name: BACKUP_HOST
          value: "primary"
        - name: BACKUP_PORT
          value: "5432"
      restartPolicy: Never
```

Here is the pod output

```
+ ose_hack
++ id -u
+ export USER_ID=26
+ USER_ID=26
++ id -g
+ export GROUP_ID=26
+ GROUP_ID=26
+ envsubst
+ export LD_PRELOAD=/usr/lib64/libnss_wrapper.so
+ LD_PRELOAD=/usr/lib64/libnss_wrapper.so
+ export NSS_WRAPPER_PASSWD=/tmp/passwd
+ NSS_WRAPPER_PASSWD=/tmp/passwd
+ export NSS_WRAPPER_GROUP=/etc/group
+ NSS_WRAPPER_GROUP=/etc/group
+ BACKUPBASE=/pgdata/primary-backups
+ '[' '!' -d /pgdata/primary-backups ']'
+ echo 'creating BACKUPBASE directory...'
+ mkdir -p /pgdata/primary-backups
creating BACKUPBASE directory...
+ [[ ! -v BACKUP_LABEL ]]
+ BACKUP_LABEL=crunchybackup
+ echo 'BACKUP_LABEL is set to ' crunchybackup
BACKUP_LABEL is set to  crunchybackup
++ date +%Y-%m-%d-%H-%M-%S
+ TS=2017-12-12-10-24-39
+ BACKUP_PATH=/pgdata/primary-backups/2017-12-12-10-24-39
+ mkdir /pgdata/primary-backups/2017-12-12-10-24-39
+ echo /pgdata/primary-backups/2017-12-12-10-24-39
+ export PGPASSFILE=/tmp/pgpass
+ PGPASSFILE=/tmp/pgpass
+ echo '*:*:*:postgres:password'
+ chmod 600 /tmp/pgpass
/pgdata/primary-backups/2017-12-12-10-24-39
+ chown 26:26 /tmp/pgpass
+ pg_basebackup --label=crunchybackup -X fetch --pgdata /pgdata/primary-backups/2017-12-12-10-24-39 --host=primary --port=5432 -U postgres
pg_basebackup: could not connect to server: FATAL:  no pg_hba.conf entry for replication connection from host "172.17.0.11", user "postgres", SSL off
+ chown -R 26:26 /pgdata/primary-backups/2017-12-12-10-24-39
+ chmod -R o+rx /pgdata/primary-backups/2017-12-12-10-24-39
+ echo 'backup has ended!'
backup has ended!
```
