### ISSUE TITLE
pgpool vs Statefulset

### ISSUE THREAD

**Issue by ghost** [CrunchyData/crunchy-containers#399]
Hi,

I have a question about kubernetes and your examples. I am using the StatefulSet to deploy a cluster of PostgreSQL. What i have understood is that the Statefulset is using replication and load balancing but does not implement the pgpool to prevent the single point of failure. So I want to use the pgpool process to do all of this.

The problem is that I do not know how to use the pgpool example. Indeed, it is creating a single pod so I cannot understand where are the master and the standby. My conclusion is that it is supposed to be used with a previous deployment: in that case, can i use it with the statefulSet?

Thanks,
Maxime

**Comment by jmccormick2001** [comment]
Hi Maxime,

the pgpool example we ship works with the primary-replica example running prior.  The pgpool example is configured to reach the service endpoints that are created from the primary-replica example.  One service is for the primary and one service is for the replica.

The statefulset example also creates 2 service endpoints, one for the primary and one for all the replicas.  So you would need to construct your pgpool configuration to use those 2 service endpoints.

hope that helps.

**Comment by ghost** [comment]
Thanks @jmccormick2001 ,

What i do not understand is that the pgpool is created with a distinct pod wereas it should be used and running within the main pods?

I have tried to achieve what you adviced me but it is not working well. This is the `yaml` file i am using to create the StatefulSet with the pgpool. Since the StatefulSet is creating the same services as the primary-replica example, it should work the same way (without any change to the startpgpool.sh)?

``` yaml
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: pgset-sa
---
apiVersion: v1
kind: Service
metadata: 
  name: pgset
  labels:
    app: pgset
spec:
  ports:
    - name: web
      port: 5432
  clusterIP: None
  selector:
    app: pgset
---
apiVersion: v1
kind: Service
metadata: 
  name: pgset-primary
  labels:
    app: pgset-primary
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
  selector:
    app: pgset
  selector:
    name: pgset-primary
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata: 
  name: pgset-replica
  labels:
    app: pgset-replica
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
  selector:
    name: pgset-replica
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata: 
  name: pgpool
  labels:
    app: pgpool
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 0
  selector:
    name: pgpool
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pgset
spec:
  serviceName: pgset
  replicas: 3
  template:
    metadata:
      labels:
        app: pgset
    spec:
      securityContext:
        fsGroup: 26
      containers:
        - name: pgset
          image: crunchydata/crunchy-postgres:centos7-10.1-1.7.0
          ports:
            - name: postgres
              containerPort: !!int 5432
          env:
            - name: PG_PRIMARY_USER
              value: primaryuser
            - name: PGHOST
              value: /tmp
            - name: PG_MODE
              value: set
            - name: PG_PRIMARY_PASSWORD
              value: password
            - name: PG_USER
              value: testuser
            - name: PG_PASSWORD
              value: password
            - name: PG_DATABASE
              value: userdb
            - name: PG_ROOT_PASSWORD
              value: password
            - name: PG_PRIMARY_PORT
              value: "5432"
            - name: PG_PRIMARY_HOST
              value: pgset-primary
          volumeMounts:
            - name: pgdata
              mountPath: /pgdata
              readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: pgdata
        annotations:
          volume.alpha.kubernetes.io/storage-class: slow
      spec:
        accessModes: [ReadWriteOnce]
        resources: 
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pgpool
  labels:
    name: pgpool
spec:
  containers:
    - name: pgpool
      image: crunchydata/crunchy-pgpool:centos7-10.1-1.7.0
      ports:
        - protocol: TCP
          containerPort: !!int 5432
      env:
        - name: PG_USERNAME
          value: testuser
        - name: PG_PASSWORD
          value: password
        - name: PG_PRIMARY_SERVICE_NAME
          value: pgset-primary
        - name: PG_REPLICA_SERVICE_NAME
          value: pgset-replica
      volumeMounts:
        - name: pgpool-conf
          mountPath: /pgconf/pgpoolconfigdir
          readOnly: false
  volumes:
    - name: pgpool-conf
      configMap: 
        name: pgpool-conf
        items:
          - key: pgpool.conf
            path: pgpool.conf
          - key: hba
            path: pool_hba.conf
          - key: psw
            path: pool_passwd
```

Thanks,
Maxime
