### ISSUE TITLE
Replica can't reach the primary in swarm mode

### ISSUE THREAD

**Issue by enigram** [CrunchyData/crunchy-containers#646]
**I'm submitting a ...**

 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

**What is the current behaviour?**
When running in a swarm with services on different nodes, the replica service cannot reach the primary using the example docker compose file located [here](https://github.com/CrunchyData/crunchy-containers/blob/master/examples/docker/swarm-service/docker-compose.yml)

**If the current behavior is a bug, please provide the steps to reproduce:**

Compose file (postgres.yml):
```
---
version: "3.3"

services:
  primary:
    hostname: 'primary'
    image: crunchydata/crunchy-postgres:centos7-10.4-1.8.3
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=10
    - MAX_WAL_SENDERS=5
    - PG_MODE=primary
    - PG_PRIMARY_USER=primaryuser
    - PG_PRIMARY_PASSWORD=password
    - PG_DATABASE=testdb
    - PG_USER=testuser
    - PG_PASSWORD=password
    - PG_ROOT_PASSWORD=password
    - PG_PRIMARY_PORT=5432
    volumes:
    - pg-primary-vol:/pgdata
    ports:
    - "5432"
    networks:
    - crunchynet
    deploy:
      placement:
        constraints:
          - node.labels.data_center == toronto
  replica:
    image: crunchydata/crunchy-postgres:centos7-10.4-1.8.3
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=10
    - MAX_WAL_SENDERS=5
    - PG_MODE=replica
    - PG_PRIMARY_HOST=primary
    - PG_PRIMARY_PORT=5432
    - PG_PRIMARY_USER=primaryuser
    - PG_PRIMARY_PASSWORD=password
    - PG_DATABASE=testdb
    - PG_USER=testuser
    - PG_PASSWORD=password
    - PG_ROOT_PASSWORD=password
    volumes:
    - pg-replica-vol:/pgdata
    ports:
    - "5432"
    networks:
    - crunchynet
    deploy:
      placement:
        constraints:
          - node.labels.data_center != toronto
networks:
  crunchynet:

volumes:
  pg-primary-vol:
  pg-replica-vol:
```
Running with:
```
docker stack deploy -c postgres.yml postgres-db
```

Logs from the primary:
```
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: Setting PGROOT to /usr/pgsql-10.
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: Cleaning up the old postmaster.pid file..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: User ID is set to uid=26(postgres) gid=26(postgres) groups=26(postgres).
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: Setting MAX_CONNECTIONS to 10.
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: Setting MAX_WAL_SENDERS to 5.
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: Working on primary..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: Initializing the primary database..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: PGDATA is empty. ID is uid=26(postgres) gid=26(postgres) groups=26(postgres). Creating the PGDATA directory..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: Checking for restore..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | total 0
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: No backup file found.
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:03 UTC 2018 INFO: Starting initdb..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | initdb -D /pgdata/primary > /tmp/initdb.log &> /tmp/initdb.err
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:05 UTC 2018 INFO: Overlaying PostgreSQL's default configuration with customized settings..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:05 UTC 2018 INFO: Checking for PITR WAL files to recover with..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:05 UTC 2018 INFO: Temporarily starting database to run setup.sql..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | waiting for server to start....2018-06-19 13:52:05 EDT [62]: [1-1] user=,db=,app=,client=LOG:  pgaudit extension initialized
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [62]: [2-1] user=,db=,app=,client=LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [62]: [3-1] user=,db=,app=,client=LOG:  listening on IPv6 address "::", port 5432
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [62]: [4-1] user=,db=,app=,client=LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [62]: [5-1] user=,db=,app=,client=LOG:  redirecting log output to logging collector process
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [62]: [6-1] user=,db=,app=,client=HINT:  Future log output will appear in directory "pg_log".
postgres-db_primary.1.vmjdl1pk8c80@node-01    |  done
postgres-db_primary.1.vmjdl1pk8c80@node-01    | server started
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:05 UTC 2018 INFO: Waiting for PostgreSQL to start..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | primary:5432 - accepting connections
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:05 UTC 2018 INFO: The database is ready for setup.sql.
postgres-db_primary.1.vmjdl1pk8c80@node-01    | SET
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE EXTENSION
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE EXTENSION
postgres-db_primary.1.vmjdl1pk8c80@node-01    | ALTER ROLE
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE ROLE
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE ROLE
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE TABLE
postgres-db_primary.1.vmjdl1pk8c80@node-01    | GRANT
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE DATABASE
postgres-db_primary.1.vmjdl1pk8c80@node-01    | GRANT
postgres-db_primary.1.vmjdl1pk8c80@node-01    | You are now connected to database "testdb" as user "postgres".
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE EXTENSION
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE EXTENSION
postgres-db_primary.1.vmjdl1pk8c80@node-01    | You are now connected to database "testdb" as user "testuser".
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE SCHEMA
postgres-db_primary.1.vmjdl1pk8c80@node-01    | CREATE TABLE
postgres-db_primary.1.vmjdl1pk8c80@node-01    | INSERT 0 1
postgres-db_primary.1.vmjdl1pk8c80@node-01    | INSERT 0 1
postgres-db_primary.1.vmjdl1pk8c80@node-01    | GRANT
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:05 UTC 2018 INFO: Stopping database after primary initialization..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | waiting for server to shut down.... done
postgres-db_primary.1.vmjdl1pk8c80@node-01    | server stopped
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:05 UTC 2018 INFO: Starting PostgreSQL..
postgres-db_primary.1.vmjdl1pk8c80@node-01    | Tue Jun 19 17:52:05 UTC 2018
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [96]: [1-1] user=,db=,app=,client=LOG:  pgaudit extension initialized
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [96]: [2-1] user=,db=,app=,client=LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [96]: [3-1] user=,db=,app=,client=LOG:  listening on IPv6 address "::", port 5432
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [96]: [4-1] user=,db=,app=,client=LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [96]: [5-1] user=,db=,app=,client=LOG:  redirecting log output to logging collector process
postgres-db_primary.1.vmjdl1pk8c80@node-01    | 2018-06-19 13:52:05 EDT [96]: [6-1] user=,db=,app=,client=HINT:  Future log output will appear in directory "pg_log".
```
Logs from the replica
```
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018 INFO: Setting PGROOT to /usr/pgsql-10.
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018 INFO: Cleaning up the old postmaster.pid file..
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018 INFO: User ID is set to uid=26(postgres) gid=26(postgres) groups=26(postgres).
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018 INFO: Setting MAX_CONNECTIONS to 10.
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018 INFO: Setting MAX_WAL_SENDERS to 5.
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018 INFO: Working on replica..
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018 INFO: Initializing the replica.
postgres-db_replica.1.eb0jyii41ig5@node-02    | Tue Jun 19 17:52:04 UTC 2018 INFO: Waiting to allow the primary database time to successfully start before performing the initial backup..
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
postgres-db_replica.1.eb0jyii41ig5@node-02    | primary:5432 - no attempt
```

**What is the expected behavior?**
The replica should find the primary service on the same stack in the swarm.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)
If I change the placement constraint so that both replica and the primary run on the same node, then it can find it with no problems. This doesn't make much sense since the example provided clearly puts the service on different nodes and uses the service name as the primary host to configure the replica. I also tried to include the stack name (postgres-db_primary) as the host name and get the same results - `postgres-db_primary:5432 - no attempt`

**Please tell us about your environment:**

 - Operating System: Ubuntu 16.04.4 LTS
 - Container Image Tag: crunchydata/crunchy-postgres:centos7-10.4-1.8.3
 - PostgreSQL Version: 10.4
 - Platform (Docker, Kubernetes, OpenShift): Docker swarm mode
 - Platform Version: Docker version 18.03.0-ce, build 0520e24

**Comment by enigram** [comment]
When inspecting one of the containers, it lists two networks (the default one and the user created)

```
"Networks": {
                "ingress": {
                    "IPAMConfig": {
                        "IPv4Address": "10.255.1.57"
                    },
                    "Links": null,
                    "Aliases": [
                        "e32e3fa3180d"
                    ],
                    "NetworkID": "pz6bi4duy82x2zgodw7jh1x90",
                    "EndpointID": "964bd9fb5044164e6a75bba2aa0d70e3849862ddc9d305ce1bf04d68dc9ad266",
                    "Gateway": "",
                    "IPAddress": "10.255.1.57",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:ff:01:39",
                    "DriverOpts": null
                },
                "postgres-db_crunchynet": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.1.9"
                    },
                    "Links": null,
                    "Aliases": [
                        "e32e3fa3180d"
                    ],
                    "NetworkID": "ph9r9a4nnxv1fpaldtlv70ua0",
                    "EndpointID": "b695b48f2150e119b7664668e58fc7428d2a238f9c82a53021039421324f59a5",
                    "Gateway": "",
                    "IPAddress": "10.0.1.9",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:01:09",
                    "DriverOpts": null
                }
```
I suspect that this has something to do with; I'm not a docker expert.

**Comment by alexsorokoletov** [comment]
This one works for me with swarm and docker 17.12

```
 primarydb:
    image: crunchydata/crunchy-postgres:centos7-9.5.13-1.8.3
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=10
    - MAX_WAL_SENDERS=5
    - PG_MODE=primary
    - PG_PRIMARY_USER=user2
    - PG_PRIMARY_PASSWORD=password2
    - PG_DATABASE=mydb
    - PG_USER=user
    - PG_PASSWORD=password
    - PG_ROOT_PASSWORD=rootpassword
    - PG_PRIMARY_PORT=5432
    volumes:
    - pg-primary-vol:/pgdata
    ports:
    - "5432"
    networks:
      - internal
    deploy:
      replicas: 1
     
  replicadb:
    image: crunchydata/crunchy-postgres:centos7-9.5.13-1.8.3
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=10
    - MAX_WAL_SENDERS=5
    - PG_MODE=replica
    - PG_PRIMARY_HOST=tasks.stackname_primarydb
    - PG_PRIMARY_PORT=5432
    - PG_PRIMARY_USER=user2
    - PG_PRIMARY_PASSWORD=password2
    - PG_DATABASE=mydb
    - PG_USER=user
    - PG_PASSWORD=password
    - PG_ROOT_PASSWORD=rootpassword
    volumes:
    - pg-replica-vol:/pgdata
    ports:
    - "5432"
    networks:
      - internal
    deploy:
      replicas: 2

```

Note I'm using `tasks.stackname_primarydb` as `PG_PRIMARY_HOST`
