### ISSUE TITLE
Master Pod Durability on Kubernetes

### ISSUE THREAD

**Issue by aleksarias** [CrunchyData/crunchy-containers#91]
Following the example for Kubernetes Helm the master pod lacks durability. Is there any way that we can make this pod durable? 
I had a node die which contained the master pod. The master pod never came back since it didn't have a replication controller or deployment.

**Comment by aleksarias** [comment]
Here's what I did to switch the master from a Pod to a Deployment release.

1. Changed to use latest Postgres container:
    crunchydata/crunchy-postgres:centos7-9.6-1.2.8
2. Created a deployment YAML for the master. Make sure to set the PGDATA_PATH_OVERRIDE environment variable. Otherwise, the database will be created with pod's host name. If this occurs, then every time the pod restarts it gets assigned a new name and therefore you'll start with an empty database. Also, make sure to set a label selector for the master container so you can then select it in the service.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chart: crunchy-postgresql-cluster-1.2.5
    heritage: Tiller
    name: ironic-duck-crunchy-master
    release: ironic-duck
  name: ironic-duck-crunchy-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: crunchy-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: crunchy-postgres
      name: crunchy-postgres
    spec:
      containers:
      - env:
        - name: PGHOST
          value: /tmp
        - name: PG_MASTER_USER
          value: master
        - name: PG_MODE
          value: master
        - name: PG_MASTER_PASSWORD
          value: password
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: password
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: password
        - name: PGDATA_PATH_OVERRIDE
          value: master-data
        image: crunchydata/crunchy-postgres:centos7-9.6-1.2.8
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100M
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /pgdata
          name: pgdata
        - mountPath: /backup
          name: backup
          readOnly: true
        - mountPath: /pguser
          name: pguser-volume
          readOnly: true
        - mountPath: /pgmaster
          name: pgmaster-volume
          readOnly: true
        - mountPath: /pgroot
          name: pgroot-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: master-nfs-pvc
      - emptyDir: {}
        name: backup
      - name: pguser-volume
        secret:
          defaultMode: 420
          secretName: pguser-secret
      - name: pgmaster-volume
        secret:
          defaultMode: 420
          secretName: pgmaster-secret
      - name: pgroot-volume
        secret:
          defaultMode: 420
          secretName: pgroot-secret
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-02-23T22:46:25Z
    lastUpdateTime: 2017-02-23T22:46:25Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
```
3. Update the master pod service to use the selector created in the deployment.
```
apiVersion: v1
kind: Service
metadata:
  labels:
    chart: crunchy-postgresql-cluster-1.2.5
    heritage: Tiller
    name: ironic-duck-crunchy-master
    release: ironic-duck
  name: postgres-master
  namespace: default
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: crunchy-postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
4. Update slave deployment to use the Postgres-master service as host
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
  generateName: ironic-duck-crunchy-replica-3910484691-
  labels:
    name: crunchy-replica
  name: ironic-duck-crunchy-replica-3910484691-qq3zz
  namespace: default
    kind: ReplicaSet
    name: ironic-duck-crunchy-replica-3910484691
spec:
  containers:
  - env:
    - name: PGHOST
      value: /tmp
    - name: PG_MASTER_HOST
      value: postgres-master
    - name: PG_MASTER_PORT
      value: "5432"
    - name: PG_MODE
      value: slave
    - name: PG_MASTER_USER
      value: master
    - name: PG_MASTER_PASSWORD
      value: password
    - name: PG_USER
      value: testuser
    - name: PG_PASSWORD
      value: password
    - name: PG_DATABASE
      value: userdb
    - name: PG_ROOT_PASSWORD
      value: password
    image: crunchydata/crunchy-postgres:centos7-9.6-1.2.8
    imagePullPolicy: IfNotPresent
    name: ironic-duck-crunchy-replica
    ports:
    - containerPort: 5432
      protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 100M
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /pgdata
      name: pgdata
    - mountPath: /backup
      name: backup
      readOnly: true
    - mountPath: /pguser
      name: pguser-volume
    - mountPath: /pgmaster
      name: pgmaster-volume
    - mountPath: /pgroot
      name: pgroot-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wzhv2
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-airportal-node-pool-1-8276a6e2-dcxw
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: pgdata
  - emptyDir: {}
    name: backup
  - name: pguser-volume
    secret:
      defaultMode: 420
      secretName: pguser-secret
  - name: pgmaster-volume
    secret:
      defaultMode: 420
      secretName: pgmaster-secret
  - name: pgroot-volume
    secret:
      defaultMode: 420
      secretName: pgroot-secret
  - name: default-token-wzhv2
    secret:
      defaultMode: 420
      secretName: default-token-wzhv2
```

I think this was everything.
